# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.redirect_to_preferred_locale_listener:
        class: MK\AppBundle\EventListener\RedirectToPreferredLocaleListener
        arguments: ['%app_locales%', '%locale%']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelRequest }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

