services:
#    mk_user.example:
#        class: MK\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    validator.contains_phone:
        class: MK\UserBundle\Validator\Constraints\ConstraintPhone
